# Generated by Django 5.1.3 on 2024-12-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='linea',
            field=models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPPORT', 'Support'), ('JUNGLE', 'Jungle')], default='TOP', max_length=10),
        ),
    ]
