# Generated by Django 5.1.3 on 2024-12-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galeria_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='linea',
            field=models.CharField(choices=[('Top', 'Top'), ('Mid', 'Mid'), ('ADC', 'ADC'), ('Support', 'Support'), ('Jungle', 'Jungle')], default='Top', max_length=10),
        ),
    ]
