# Generated by Django 5.1.3 on 2024-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galeria_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='tipo',
            field=models.CharField(choices=[('Asesino', 'Asesino'), ('Tanque', 'Tanque'), ('Mago', 'Mago'), ('Tirador', 'Tirador'), ('Soporte', 'Soporte')], default='Asesino', max_length=10),
        ),
    ]
