# Generated by Django 5.1.3 on 2024-12-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galeria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galeria'),
        ),
    ]
